"""Deployment parity: the blueprint must not drift from config.py.

Adding a setting and forgetting to declare it is the classic way to get a deploy that
behaves differently from your laptop — silently, and usually only in the feature you just
shipped. These tests fail the moment the two disagree.

render.yaml is parsed with a regex rather than a YAML library: this is the only YAML in the
project and it isn't worth a runtime dependency for one file.
"""

from __future__ import annotations

import pathlib
import re

from inais.config import Settings

ROOT = pathlib.Path(__file__).resolve().parents[1]
RENDER_YAML = ROOT / "render.yaml"
ENV_EXAMPLE = ROOT / ".env.example"

# Injected by Render itself. Declaring RENDER_EXTERNAL_URL would let a typo break webhook
# delivery, so it is intentionally absent from the blueprint.
RENDER_PROVIDED = {"RENDER_EXTERNAL_URL"}

# Values that must never be committed — the blueprint has to prompt for them instead.
MUST_BE_SECRET = {
    "TELEGRAM_BOT_TOKEN", "OWNER_TELEGRAM_ID", "ANTHROPIC_API_KEY", "OPENAI_API_KEY",
    "SUPABASE_DB_URL", "BINANCE_API_KEY", "BINANCE_API_SECRET",
    "TAVILY_API_KEY", "BRAVE_API_KEY",
}


def config_keys() -> set[str]:
    return {name.upper() for name in Settings.model_fields}


def blueprint_text() -> str:
    return RENDER_YAML.read_text(encoding="utf-8")


def blueprint_entries() -> dict[str, str]:
    """key -> the block of YAML that follows it (value / sync / generateValue lines)."""
    text = blueprint_text()
    entries: dict[str, str] = {}
    matches = list(re.finditer(r"^\s*-\s*key:\s*([A-Z0-9_]+)\s*$", text, re.M))
    for i, m in enumerate(matches):
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        entries[m.group(1)] = text[m.end():end]
    return entries


def test_blueprint_declares_every_config_field():
    missing = config_keys() - set(blueprint_entries()) - RENDER_PROVIDED
    assert not missing, f"render.yaml is missing: {sorted(missing)}"


def test_blueprint_declares_nothing_unknown():
    """A stale key in the blueprint is dead weight that reads as if it still works."""
    extra = set(blueprint_entries()) - config_keys()
    assert not extra, f"render.yaml declares unknown settings: {sorted(extra)}"


def test_secrets_are_never_committed_to_the_blueprint():
    entries = blueprint_entries()
    for key in MUST_BE_SECRET:
        assert key in entries, f"{key} must be declared in render.yaml"
        assert "sync: false" in entries[key], f"{key} must be sync: false, not a literal value"
        assert "value:" not in entries[key], f"{key} must not carry a committed value"


def test_generated_secrets_are_generated_not_prompted():
    entries = blueprint_entries()
    for key in ("TELEGRAM_WEBHOOK_SECRET", "WEBHOOK_SECRET_PATH"):
        assert "generateValue: true" in entries[key], f"{key} should be generated by Render"


def _setting(name: str, value: str) -> str:
    """Match `name: value`, tolerating the trailing comments the blueprint uses."""
    return rf"^\s*{name}:\s*{value}\s*(#.*)?$"


def test_service_shape_is_a_single_docker_web_service_with_a_health_check():
    text = blueprint_text()
    assert re.search(r"^\s*-\s*type:\s*web\s*(#.*)?$", text, re.M)
    assert re.search(_setting("runtime", "docker"), text, re.M)
    assert re.search(_setting("healthCheckPath", "/healthz"), text, re.M)
    assert len(re.findall(r"^\s*-\s*type:\s*\w+", text, re.M)) == 1, "expected exactly one service"


def test_blueprint_pins_a_single_instance():
    """Two instances would mean two schedulers: every reminder and brief sent twice."""
    assert re.search(_setting("numInstances", "1"), blueprint_text(), re.M)


def test_blueprint_stays_on_an_always_on_plan():
    """The free plan sleeps after 15 idle minutes, which stops every background job."""
    assert re.search(_setting("plan", r"(starter|standard|pro)"), blueprint_text(), re.M)


def test_health_check_path_is_actually_served():
    main = (ROOT / "src" / "inais" / "main.py").read_text(encoding="utf-8")
    assert '"/healthz"' in main, "healthCheckPath must match a real route in main.py"


def test_run_mode_is_web_in_production():
    assert "value: web" in blueprint_entries()["RUN_MODE"]


def test_env_example_documents_every_field():
    documented = set(re.findall(r"^([A-Z0-9_]+)=", ENV_EXAMPLE.read_text(encoding="utf-8"), re.M))
    missing = config_keys() - documented - RENDER_PROVIDED
    assert not missing, f".env.example is missing: {sorted(missing)}"


def test_env_example_ships_no_real_secrets():
    """Every secret line must be empty (KEY=) so a copied .env can't leak someone's key."""
    text = ENV_EXAMPLE.read_text(encoding="utf-8")
    for key in MUST_BE_SECRET:
        for line in text.splitlines():
            if line.startswith(f"{key}="):
                value = line.split("=", 1)[1].split("#")[0].strip()
                assert not value, f".env.example must not ship a value for {key}"


def test_migrations_do_not_require_a_bot_token():
    """Documented deploy order applies migrations before the bot is configured (and in CI)."""
    from inais.config import DbSettings

    assert DbSettings().model_dump().keys() == {"supabase_db_url"}


def test_migration_runner_uses_the_minimal_settings():
    runner = (ROOT / "scripts" / "apply_migrations.py").read_text(encoding="utf-8")
    assert "db_settings" in runner and "import settings" not in runner
