"""Deployment parity: the blueprint must not drift from config.py.

Adding a setting and forgetting to declare it is the classic way to get a deploy that
behaves differently from your laptop — silently, and usually only in the feature you just
shipped. These tests fail the moment the two disagree.

render.yaml is parsed with a regex rather than a YAML library: this is the only YAML in the
project and it isn't worth a runtime dependency for one file.
"""

from __future__ import annotations

import pathlib
import re

from inais.config import Settings

ROOT = pathlib.Path(__file__).resolve().parents[1]
RENDER_YAML = ROOT / "render.yaml"
ENV_EXAMPLE = ROOT / ".env.example"

# Injected by Render itself. Declaring RENDER_EXTERNAL_URL would let a typo break webhook
# delivery, so it is intentionally absent from the blueprint.
RENDER_PROVIDED = {"RENDER_EXTERNAL_URL"}

# Values that must never be committed — the blueprint has to prompt for them instead.
MUST_BE_SECRET = {
    "TELEGRAM_BOT_TOKEN", "OWNER_TELEGRAM_ID", "ANTHROPIC_API_KEY", "OPENAI_API_KEY",
    "SUPABASE_DB_URL", "BINANCE_API_KEY", "BINANCE_API_SECRET",
    "TAVILY_API_KEY", "BRAVE_API_KEY",
}


def config_keys() -> set[str]:
    return {name.upper() for name in Settings.model_fields}


def blueprint_text() -> str:
    return RENDER_YAML.read_text(encoding="utf-8")


def blueprint_entries() -> dict[str, str]:
    """key -> the block of YAML that follows it (value / sync / generateValue lines)."""
    text = blueprint_text()
    entries: dict[str, str] = {}
    matches = list(re.finditer(r"^\s*-\s*key:\s*([A-Z0-9_]+)\s*$", text, re.M))
    for i, m in enumerate(matches):
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        entries[m.group(1)] = text[m.end():end]
    return entries


def test_blueprint_declares_every_config_field():
    missing = config_keys() - set(blueprint_entries()) - RENDER_PROVIDED
    assert not missing, f"render.yaml is missing: {sorted(missing)}"


def test_blueprint_declares_nothing_unknown():
    """A stale key in the blueprint is dead weight that reads as if it still works."""
    extra = set(blueprint_entries()) - config_keys()
    assert not extra, f"render.yaml declares unknown settings: {sorted(extra)}"


def test_secrets_are_never_committed_to_the_blueprint():
    entries = blueprint_entries()
    for key in MUST_BE_SECRET:
        assert key in entries, f"{key} must be declared in render.yaml"
        assert "sync: false" in entries[key], f"{key} must be sync: false, not a literal value"
        assert "value:" not in entries[key], f"{key} must not carry a committed value"


def test_generated_secrets_are_generated_not_prompted():
    entries = blueprint_entries()
    for key in ("TELEGRAM_WEBHOOK_SECRET", "WEBHOOK_SECRET_PATH"):
        assert "generateValue: true" in entries[key], f"{key} should be generated by Render"


def _setting(name: str, value: str) -> str:
    """Match `name: value`, tolerating the trailing comments the blueprint uses."""
    return rf"^\s*{name}:\s*{value}\s*(#.*)?$"


def test_service_shape_is_a_single_docker_web_service_with_a_health_check():
    text = blueprint_text()
    assert re.search(r"^\s*-\s*type:\s*web\s*(#.*)?$", text, re.M)
    assert re.search(_setting("runtime", "docker"), text, re.M)
    assert re.search(_setting("healthCheckPath", "/healthz"), text, re.M)
    assert len(re.findall(r"^\s*-\s*type:\s*\w+", text, re.M)) == 1, "expected exactly one service"


def test_blueprint_pins_a_single_instance():
    """Two instances would mean two schedulers: every reminder and brief sent twice."""
    assert re.search(_setting("numInstances", "1"), blueprint_text(), re.M)


def test_blueprint_stays_on_an_always_on_plan():
    """The free plan sleeps after 15 idle minutes, which stops every background job."""
    assert re.search(_setting("plan", r"(starter|standard|pro)"), blueprint_text(), re.M)


def test_health_check_path_is_actually_served():
    main = (ROOT / "src" / "inais" / "main.py").read_text(encoding="utf-8")
    assert '"/healthz"' in main, "healthCheckPath must match a real route in main.py"


def test_run_mode_is_web_in_production():
    assert "value: web" in blueprint_entries()["RUN_MODE"]


def test_env_example_documents_every_field():
    documented = set(re.findall(r"^([A-Z0-9_]+)=", ENV_EXAMPLE.read_text(encoding="utf-8"), re.M))
    missing = config_keys() - documented - RENDER_PROVIDED
    assert not missing, f".env.example is missing: {sorted(missing)}"


def test_env_example_ships_no_real_secrets():
    """Every secret line must be empty (KEY=) so a copied .env can't leak someone's key."""
    text = ENV_EXAMPLE.read_text(encoding="utf-8")
    for key in MUST_BE_SECRET:
        for line in text.splitlines():
            if line.startswith(f"{key}="):
                value = line.split("=", 1)[1].split("#")[0].strip()
                assert not value, f".env.example must not ship a value for {key}"


def test_setup_scripts_do_not_require_a_bot_token():
    """Migrations and Gmail auth both run BEFORE the bot is configured."""
    from inais.config import ScriptSettings

    fields = set(ScriptSettings().model_dump())
    assert "telegram_bot_token" not in fields
    assert "owner_telegram_id" not in fields
    assert {"supabase_db_url", "google_oauth_client_json"} <= fields


def test_setup_scripts_use_the_minimal_settings():
    for name in ("apply_migrations.py", "authorize_gmail.py"):
        source = (ROOT / "scripts" / name).read_text(encoding="utf-8")
        assert "script_settings" in source, name
        assert "import settings" not in source, name


# ---------- database connection string validation ----------

def test_project_url_is_rejected_with_a_useful_message():
    """The real production failure: pasting the Supabase project URL, not the Postgres URI."""
    from inais.db import dsn_problem

    problem = dsn_problem("https://exhqskmdipcydkayaufu.supabase.co")
    assert problem is not None
    assert "project URL" in problem
    assert "Session pooler" in problem      # tells them exactly where to look


def test_unreplaced_password_placeholder_is_caught():
    from inais.db import dsn_problem

    dsn = "postgresql://postgres.abc:[YOUR-PASSWORD]@aws-0-eu-west-1.pooler.supabase.com:5432/postgres"
    assert "placeholder password" in (dsn_problem(dsn) or "")


def test_wrong_scheme_names_the_scheme_it_got():
    from inais.db import dsn_problem

    assert "mysql" in (dsn_problem("mysql://u:p@h/db") or "")


def test_hostless_dsn_is_rejected():
    from inais.db import dsn_problem

    assert dsn_problem("postgresql://justtext") is not None


def test_valid_pooler_uris_pass():
    from inais.db import dsn_problem

    for dsn in (
        "postgresql://postgres.abc:pw@aws-0-eu-west-1.pooler.supabase.com:5432/postgres",
        "postgres://postgres:pw@db.abc.supabase.co:5432/postgres",
        "postgresql://postgres.abc:pw@aws-0-us-east-1.pooler.supabase.com:6543/postgres",
    ):
        assert dsn_problem(dsn) is None


def test_empty_dsn_is_not_a_problem_just_a_disabled_feature():
    from inais.db import dsn_problem

    assert dsn_problem("") is None
    assert dsn_problem(None) is None


# ---------- webhook secret / path sanitisation ----------

def _settings(**over):
    from inais.config import Settings

    base = {"telegram_bot_token": "123456:ABCdef", "owner_telegram_id": 1}
    base.update(over)
    return Settings(**base)


def test_generated_secret_is_filtered_to_telegrams_alphabet():
    """Telegram rejects setWebhook outright for anything outside A-Z a-z 0-9 _ - ."""
    import re

    secret = _settings(telegram_webhook_secret="aB3+xy/z=Qw==").webhook_secret
    assert re.fullmatch(r"[A-Za-z0-9_-]+", secret)
    assert "+" not in secret and "/" not in secret and "=" not in secret


def test_webhook_secret_is_stable_for_the_same_input():
    """setWebhook and the request check read the same property — they must never disagree."""
    a = _settings(telegram_webhook_secret="aB3+xy/z=").webhook_secret
    b = _settings(telegram_webhook_secret="aB3+xy/z=").webhook_secret
    assert a == b


def test_missing_secret_still_yields_a_verifiable_token():
    """No secret used to mean no verification at all; derive one instead."""
    secret = _settings(telegram_webhook_secret="").webhook_secret
    assert len(secret) >= 32


def test_secret_of_only_invalid_characters_falls_back():
    assert len(_settings(telegram_webhook_secret="+/=+/=").webhook_secret) >= 32


def test_webhook_secret_respects_telegrams_length_cap():
    assert len(_settings(telegram_webhook_secret="a" * 400).webhook_secret) <= 256


def test_webhook_path_never_contains_a_slash():
    """A generated '/' would silently split the route and every update would 404."""
    path = _settings(webhook_secret_path="p+a/th=").webhook_path
    assert "/" not in path and path == "path"


def test_webhook_path_falls_back_to_a_hex_digest():
    import re

    path = _settings(webhook_secret_path="").webhook_path
    assert re.fullmatch(r"[0-9a-f]{32}", path)


# ---------- brain provider switch ----------

def test_provider_auto_prefers_anthropic_then_falls_back():
    assert _settings(anthropic_api_key="k", openai_api_key="k").agent_provider == "anthropic"
    assert _settings(anthropic_api_key="", openai_api_key="k").agent_provider == "openai"


def test_provider_can_be_forced_to_openai():
    """The case this exists for: a key is present but the account has no Claude access."""
    cfg = _settings(brain_provider="openai", anthropic_api_key="k", openai_api_key="k")
    assert cfg.agent_provider == "openai"
    assert cfg.resolved_agent_model == cfg.openai_agent_model
    assert cfg.resolved_subagent_model == cfg.triage_model


def test_forced_openai_needs_only_an_openai_key():
    assert _settings(brain_provider="openai", anthropic_api_key="",
                     openai_api_key="k").brain_enabled


def test_anthropic_brain_still_needs_both_keys():
    assert not _settings(brain_provider="anthropic", anthropic_api_key="k",
                         openai_api_key="").brain_enabled


def test_unknown_provider_value_falls_back_to_auto():
    assert _settings(brain_provider="banana", anthropic_api_key="k").agent_provider == "anthropic"


# ---------- provider-neutral message conversion ----------

NEUTRAL = [
    {"role": "user", "content": "hello"},
    {"role": "assistant", "text": "checking",
     "tool_calls": [{"id": "c1", "name": "get_portfolio", "input": {"x": 1}}]},
    {"role": "tool_results", "results": [{"id": "c1", "content": "BTC 0.5"}]},
]


def test_anthropic_conversion_shapes_tool_blocks():
    from inais.llm import to_anthropic_messages

    out = to_anthropic_messages(NEUTRAL)
    assert [m["role"] for m in out] == ["user", "assistant", "user"]
    assert out[1]["content"][1]["type"] == "tool_use"
    assert out[1]["content"][1]["id"] == "c1"
    assert out[2]["content"][0]["type"] == "tool_result"
    assert out[2]["content"][0]["tool_use_id"] == "c1"


def test_openai_conversion_shapes_tool_calls():
    import json

    from inais.llm import to_openai_messages

    out = to_openai_messages(NEUTRAL, "SYSTEM")
    assert out[0] == {"role": "system", "content": "SYSTEM"}
    assert [m["role"] for m in out] == ["system", "user", "assistant", "tool"]
    call = out[2]["tool_calls"][0]
    assert call["function"]["name"] == "get_portfolio"
    assert json.loads(call["function"]["arguments"]) == {"x": 1}
    assert out[3]["tool_call_id"] == "c1"


def test_images_convert_to_openais_data_url():
    from inais.llm import to_openai_messages

    neutral = [{"role": "user", "content": [
        {"type": "image", "source": {"type": "base64", "media_type": "image/png", "data": "AAA"}},
        {"type": "text", "text": "what is this"},
    ]}]
    block = to_openai_messages(neutral, "S")[1]["content"][0]
    assert block["type"] == "image_url"
    assert block["image_url"]["url"] == "data:image/png;base64,AAA"


def test_tool_schema_conversion_keeps_the_parameters():
    from inais.llm import tools_to_openai

    tools = [{"name": "t", "description": "d",
              "input_schema": {"type": "object", "properties": {"a": {"type": "string"}}}}]
    out = tools_to_openai(tools)[0]
    assert out["type"] == "function"
    assert out["function"]["name"] == "t"
    assert out["function"]["parameters"]["properties"]["a"]["type"] == "string"


# ---------- no null content reaches either provider ----------

TOOL_TURN_NO_TEXT = [
    {"role": "user", "content": "what's my portfolio worth?"},
    # the real shape that broke production: tool calls with no accompanying prose
    {"role": "assistant", "text": "", "tool_calls": [
        {"id": "c1", "name": "get_portfolio", "input": {}}]},
    {"role": "tool_results", "results": [{"id": "c1", "content": "BTC 0.5"}]},
]


def test_tool_call_without_text_omits_content_rather_than_nulling_it():
    """OpenAI 400s on content: null — this exact turn broke the deployed bot."""
    from inais.llm import to_openai_messages

    out = to_openai_messages(TOOL_TURN_NO_TEXT, "S")
    assistant = next(m for m in out if m["role"] == "assistant")
    assert assistant.get("content", "not-null") is not None
    assert "tool_calls" in assistant


def test_no_message_ever_carries_null_content():
    from inais.llm import to_anthropic_messages, to_openai_messages

    cases = [
        TOOL_TURN_NO_TEXT,
        [{"role": "user", "content": None}],
        [{"role": "assistant", "text": None, "tool_calls": []}],
        [{"role": "assistant", "text": "with prose", "tool_calls": [
            {"id": "c", "name": "n", "input": {}}]}],
    ]
    for case in cases:
        for msg in to_openai_messages(case, "S") + to_anthropic_messages(case):
            assert msg.get("content", "") is not None, f"null content from {case}"


def test_assistant_text_alongside_tool_calls_is_preserved():
    from inais.llm import to_openai_messages

    case = [{"role": "assistant", "text": "checking that now",
             "tool_calls": [{"id": "c", "name": "n", "input": {}}]}]
    assistant = to_openai_messages(case, "S")[1]
    assert assistant["content"] == "checking that now"
    assert len(assistant["tool_calls"]) == 1


def test_status_reports_the_model_actually_in_use():
    """Showing AGENT_MODEL while running on OpenAI made /status lie about the brain."""
    cfg = _settings(brain_provider="openai", anthropic_api_key="k", openai_api_key="k",
                    agent_model="claude-sonnet-5", openai_agent_model="gpt-5")
    assert cfg.resolved_agent_model == "gpt-5"
    assert cfg.agent_provider == "openai"


# ---------- automatic provider fallback ----------

def test_a_dead_anthropic_key_is_recognised_as_fatal():
    """The real error: 401 invalid x-api-key. Retrying that forever is a dead assistant."""
    from inais.llm import _anthropic_is_unusable

    real = ("Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', "
            "'message': 'invalid x-api-key'}}")
    assert _anthropic_is_unusable(Exception(real))


def test_other_fatal_anthropic_conditions_are_covered():
    from inais.llm import _anthropic_is_unusable

    for message in ("not_found_error: model not found",
                    "Your credit balance is too low",
                    "permission_error"):
        assert _anthropic_is_unusable(Exception(message))


def test_transient_errors_do_not_trigger_a_switch():
    """A timeout or overload must not permanently move the brain off its configured provider."""
    from inais.llm import _anthropic_is_unusable

    for message in ("529 overloaded", "request timed out", "internal server error"):
        assert not _anthropic_is_unusable(Exception(message))
