"""PDF markdown→HTML conversion and real PDF byte output."""

from __future__ import annotations

from inais.integrations.pdf import build_pdf, markdown_to_html


def test_headings_bullets_and_numbers_become_html():
    md = "# H1\n## H2\n### H3\n- a\n- b\n1. one\n2. two\n\nA paragraph."
    h = markdown_to_html("Title", md)
    assert "<h1>Title</h1>" in h
    assert "<h2>H1</h2>" in h and "<h2>H2</h2>" in h and "<h3>H3</h3>" in h
    assert h.count("<ul>") == 1 and h.count("<ol>") == 1
    assert "<li>a</li>" in h and "<li>one</li>" in h
    assert "<p>A paragraph.</p>" in h


def test_inline_bold_and_code():
    h = markdown_to_html("T", "text with **bold** and `code`")
    assert "<b>bold</b>" in h and "<code>code</code>" in h


def test_html_in_content_is_escaped_not_injected():
    """User/model text must never inject markup into the document."""
    h = markdown_to_html("<script>x</script>", "body <b>raw</b> & <i>tags</i>")
    assert "<script>" not in h
    assert "&lt;script&gt;" in h
    assert "&lt;b&gt;raw&lt;/b&gt;" in h        # literal, not applied
    assert "&amp;" in h


def test_subtitle_is_rendered_when_present():
    assert "class=\"meta\"" in markdown_to_html("T", "body", subtitle="by INAIS")
    assert "class=\"meta\"" not in markdown_to_html("T", "body")


def test_build_pdf_returns_a_valid_pdf():
    data = build_pdf("Report", "# Section\nSome text.\n\n- point one\n- point two",
                     "Generated by INAIS")
    assert data[:5] == b"%PDF-"
    assert len(data) > 500

    import pymupdf

    doc = pymupdf.open(stream=data, filetype="pdf")
    assert doc.page_count >= 1
    text = doc[0].get_text("text")
    assert "Report" in text and "Section" in text and "point one" in text


def test_empty_body_still_produces_a_pdf():
    data = build_pdf("Just a title", "")
    assert data[:5] == b"%PDF-"
